from django.urls import path

from .views import (
    admin_courses,
    admin_course_detail,
    admin_course_enrollments,
    admin_insights,
    admin_lessons,
    admin_lesson_detail,
    admin_quizzes,
    admin_quiz_detail,
    admin_sections,
    admin_upload_hls_metadata,
    admin_upload_video,
    course_access,
    course_detail,
    course_lessons,
    course_list,
    enroll_course,
    health_check,
    lesson_detail,
    lesson_progress,
    lesson_quiz,
    logout,
    me,
    my_enrollments,
    quiz_attempts,
    quiz_submit,
    register,
    stream_access,
    stream_hls_asset,
    stream_heartbeat,
    stream_renew,
)

urlpatterns = [
    path("admin/courses/", admin_courses, name="admin-courses"),
    path("admin/courses/<int:course_id>/", admin_course_detail, name="admin-course-detail"),
    path("admin/courses/<int:course_id>/enrollments/", admin_course_enrollments, name="admin-course-enrollments"),
    path("admin/insights/", admin_insights, name="admin-insights"),
    path("admin/lessons/", admin_lessons, name="admin-lessons"),
    path("admin/lessons/<int:lesson_id>/", admin_lesson_detail, name="admin-lesson-detail"),
    path("admin/quizzes/", admin_quizzes, name="admin-quizzes"),
    path("admin/quizzes/<int:quiz_id>/", admin_quiz_detail, name="admin-quiz-detail"),
    path("admin/sections/", admin_sections, name="admin-sections"),
    path("admin/upload-hls-metadata/", admin_upload_hls_metadata, name="admin-upload-hls"),
    path("admin/upload-video/", admin_upload_video, name="admin-upload-video"),
    path("auth/register/", register, name="register"),
    path("auth/logout/", logout, name="logout"),
    path("courses/", course_list, name="course-list"),
    path("courses/<int:course_id>/access/", course_access, name="course-access"),
    path("courses/<int:course_id>/enroll/", enroll_course, name="enroll-course"),
    path("courses/<int:course_id>/lessons/", course_lessons, name="course-lessons"),
    path("courses/<slug:course_slug>/", course_detail, name="course-detail"),
    path("health/", health_check, name="health-check"),
    path("lessons/<int:lesson_id>/", lesson_detail, name="lesson-detail"),
    path("lessons/<int:lesson_id>/progress/", lesson_progress, name="lesson-progress"),
    path("lessons/<int:lesson_id>/quiz/", lesson_quiz, name="lesson-quiz"),
    path("lessons/<int:lesson_id>/stream-access/", stream_access, name="stream-access"),
    path("me/", me, name="me"),
    path("me/enrollments/", my_enrollments, name="my-enrollments"),
    path("quizzes/<int:quiz_id>/submit/", quiz_submit, name="quiz-submit"),
    path("quizzes/<int:quiz_id>/attempts/", quiz_attempts, name="quiz-attempts"),
    path("stream/heartbeat/", stream_heartbeat, name="stream-heartbeat"),
    path("stream/renew/", stream_renew, name="stream-renew"),
    path("stream/hls/<int:lesson_id>/<path:asset_name>", stream_hls_asset, name="stream-hls-asset"),
]
