from django.urls import path

from .views import (
    admin_courses,
    admin_course_detail,
    admin_course_final_exam,
    admin_course_final_exam_publish,
    admin_course_final_exam_reset,
    admin_course_enrollments,
    admin_final_exam_question_detail,
    admin_insights,
    admin_lessons,
    admin_lesson_detail,
    admin_quizzes,
    admin_quiz_detail,
    admin_sections,
    admin_student_wallet,
    admin_student_wallet_adjust,
    admin_student_expel,
    admin_students,
    admin_student_profile,
    admin_student_profile_review,
    admin_upload_hls_metadata,
    admin_upload_video,
    course_access,
    course_detail,
    course_final_exam,
    course_final_exam_attempts,
    course_exam_eligibility,
    course_lessons,
    course_list,
    enroll_course,
    health_check,
    lesson_detail,
    lesson_progress,
    lesson_quiz,
    logout,
    me,
    my_course_certificate,
    my_enrollments,
    my_profile,
    my_wallet,
    quiz_attempts,
    quiz_submit,
    register,
    username_available,
    submit_course_final_exam,
    stream_access,
    stream_hls_asset,
    stream_heartbeat,
    stream_renew,
)

urlpatterns = [
    path("admin/courses/", admin_courses, name="admin-courses"),
    path("admin/courses/<int:course_id>/", admin_course_detail, name="admin-course-detail"),
    path("admin/courses/<int:course_id>/final-exam/", admin_course_final_exam, name="admin-course-final-exam"),
    path("admin/courses/<int:course_id>/final-exam/publish/", admin_course_final_exam_publish, name="admin-course-final-exam-publish"),
    path("admin/courses/<int:course_id>/final-exam/reset/", admin_course_final_exam_reset, name="admin-course-final-exam-reset"),
    path("admin/final-exam/questions/<int:question_id>/", admin_final_exam_question_detail, name="admin-final-exam-question-detail"),
    path("admin/courses/<int:course_id>/enrollments/", admin_course_enrollments, name="admin-course-enrollments"),
    path("admin/insights/", admin_insights, name="admin-insights"),
    path("admin/lessons/", admin_lessons, name="admin-lessons"),
    path("admin/lessons/<int:lesson_id>/", admin_lesson_detail, name="admin-lesson-detail"),
    path("admin/quizzes/", admin_quizzes, name="admin-quizzes"),
    path("admin/quizzes/<int:quiz_id>/", admin_quiz_detail, name="admin-quiz-detail"),
    path("admin/sections/", admin_sections, name="admin-sections"),
    path("admin/students/", admin_students, name="admin-students"),
    path("admin/students/<int:user_id>/profile/", admin_student_profile, name="admin-student-profile"),
    path("admin/students/<int:user_id>/profile/review/", admin_student_profile_review, name="admin-student-profile-review"),
    path("admin/students/<int:user_id>/wallet/", admin_student_wallet, name="admin-student-wallet"),
    path("admin/students/<int:user_id>/wallet/adjust/", admin_student_wallet_adjust, name="admin-student-wallet-adjust"),
    path("admin/students/<int:user_id>/expel/", admin_student_expel, name="admin-student-expel"),
    path("admin/upload-hls-metadata/", admin_upload_hls_metadata, name="admin-upload-hls"),
    path("admin/upload-video/", admin_upload_video, name="admin-upload-video"),
    path("auth/register/", register, name="register"),
    path("auth/username-available/", username_available, name="username-available"),
    path("auth/logout/", logout, name="logout"),
    path("courses/", course_list, name="course-list"),
    path("courses/<int:course_id>/access/", course_access, name="course-access"),
    path("courses/<int:course_id>/enroll/", enroll_course, name="enroll-course"),
    path("courses/<int:course_id>/lessons/", course_lessons, name="course-lessons"),
    path("courses/<int:course_id>/exam-eligibility/", course_exam_eligibility, name="course-exam-eligibility"),
    path("courses/<int:course_id>/final-exam/", course_final_exam, name="course-final-exam"),
    path("courses/<int:course_id>/final-exam/submit/", submit_course_final_exam, name="submit-course-final-exam"),
    path("courses/<int:course_id>/final-exam/attempts/", course_final_exam_attempts, name="course-final-exam-attempts"),
    path("courses/<int:course_id>/certificate/", my_course_certificate, name="my-course-certificate"),
    path("courses/<slug:course_slug>/", course_detail, name="course-detail"),
    path("health/", health_check, name="health-check"),
    path("lessons/<int:lesson_id>/", lesson_detail, name="lesson-detail"),
    path("lessons/<int:lesson_id>/progress/", lesson_progress, name="lesson-progress"),
    path("lessons/<int:lesson_id>/quiz/", lesson_quiz, name="lesson-quiz"),
    path("lessons/<int:lesson_id>/stream-access/", stream_access, name="stream-access"),
    path("me/", me, name="me"),
    path("me/enrollments/", my_enrollments, name="my-enrollments"),
    path("me/profile/", my_profile, name="my-profile"),
    path("me/wallet/", my_wallet, name="my-wallet"),
    path("quizzes/<int:quiz_id>/submit/", quiz_submit, name="quiz-submit"),
    path("quizzes/<int:quiz_id>/attempts/", quiz_attempts, name="quiz-attempts"),
    path("stream/heartbeat/", stream_heartbeat, name="stream-heartbeat"),
    path("stream/renew/", stream_renew, name="stream-renew"),
    path("stream/hls/<int:lesson_id>/<path:asset_name>", stream_hls_asset, name="stream-hls-asset"),
]
