# Generated by Django 6.0.2 on 2026-02-27 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='content_type',
            field=models.CharField(choices=[('VIDEO', 'Video'), ('READING', 'Reading')], default='VIDEO', max_length=16),
        ),
        migrations.AddField(
            model_name='lesson',
            name='reading_content',
            field=models.TextField(blank=True),
        ),
    ]
