# Generated by Django 6.0.2 on 2026-02-27 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def forward_backfill_json(apps, schema_editor):
    Lesson = apps.get_model("core", "Lesson")
    Quiz = apps.get_model("core", "Quiz")
    QuizAttempt = apps.get_model("core", "QuizAttempt")
    QuizAttemptAnswer = apps.get_model("core", "QuizAttemptAnswer")

    # Backfill section fields from old Section FK.
    for lesson in Lesson.objects.select_related("section").all():
        if getattr(lesson, "section_id", None):
            lesson.section_order = lesson.section.order
            lesson.section_title = lesson.section.title
            lesson.save(update_fields=["section_order", "section_title"])

    # Backfill quiz JSON payload from old normalized quiz tables.
    for quiz in Quiz.objects.prefetch_related("questions__choices").all():
        questions = []
        for q in quiz.questions.all().order_by("order", "id"):
            choices = []
            for c in q.choices.all().order_by("id"):
                choices.append(
                    {
                        "id": c.id,
                        "text": c.text,
                        "is_correct": bool(c.is_correct),
                    }
                )
            questions.append(
                {
                    "id": q.id,
                    "prompt": q.prompt,
                    "type": q.type,
                    "order": q.order,
                    "choices": choices,
                }
            )

        lesson = quiz.lesson
        lesson.quiz_payload = {
            "passing_score": int(quiz.passing_score),
            "time_limit_sec": quiz.time_limit_sec,
            "questions": questions,
        }
        lesson.save(update_fields=["quiz_payload"])

    # Backfill attempt.lesson and attempt.answers_payload
    answers_by_attempt = {}
    for answer in QuizAttemptAnswer.objects.select_related("question", "choice").all():
        answers_by_attempt.setdefault(answer.attempt_id, []).append(
            {
                "question_id": answer.question_id,
                "choice_id": answer.choice_id,
            }
        )

    for attempt in QuizAttempt.objects.select_related("quiz__lesson").all():
        attempt.lesson_id = attempt.quiz.lesson_id
        attempt.answers_payload = answers_by_attempt.get(attempt.id, [])
        attempt.save(update_fields=["lesson", "answers_payload"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_lesson_content_type_lesson_reading_content"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="quiz_payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="lesson",
            name="section_order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="lesson",
            name="section_title",
            field=models.CharField(default="Section 1", max_length=255),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="answers_payload",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="quizattempt",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="core.lesson",
            ),
        ),
        migrations.RunPython(forward_backfill_json, migrations.RunPython.noop),
        migrations.RemoveConstraint(
            model_name="quizattemptanswer",
            name="uniq_attempt_question",
        ),
        migrations.RemoveConstraint(
            model_name="quizquestion",
            name="uniq_question_quiz_order",
        ),
        migrations.RemoveConstraint(
            model_name="section",
            name="uniq_section_course_order",
        ),
        migrations.AlterField(
            model_name="quizattempt",
            name="lesson",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quiz_attempts",
                to="core.lesson",
            ),
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"ordering": ["course_id", "section_order", "order", "id"]},
        ),
        migrations.RemoveConstraint(
            model_name="lesson",
            name="uniq_lesson_section_order",
        ),
        migrations.RemoveIndex(
            model_name="quizattempt",
            name="core_quizat_user_id_122768_idx",
        ),
        migrations.AddIndex(
            model_name="quizattempt",
            index=models.Index(fields=["user", "lesson"], name="core_quizat_user_id_ded8c0_idx"),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("course", "section_order", "order"),
                name="uniq_lesson_course_section_order",
            ),
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="section",
        ),
        migrations.RemoveField(
            model_name="quizattempt",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quizattemptanswer",
            name="attempt",
        ),
        migrations.RemoveField(
            model_name="quizattemptanswer",
            name="choice",
        ),
        migrations.RemoveField(
            model_name="quizattemptanswer",
            name="question",
        ),
        migrations.RemoveField(
            model_name="quizchoice",
            name="question",
        ),
        migrations.RemoveField(
            model_name="quizquestion",
            name="quiz",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="lesson",
        ),
        migrations.RemoveField(
            model_name="section",
            name="course",
        ),
        migrations.DeleteModel(name="QuizAttemptAnswer"),
        migrations.DeleteModel(name="QuizChoice"),
        migrations.DeleteModel(name="QuizQuestion"),
        migrations.DeleteModel(name="Quiz"),
        migrations.DeleteModel(name="Section"),
    ]
