# Generated by Django 6.0.2 on 2026-02-28 12:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_creditwallet_credittransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalExamSession",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("question_ids", models.JSONField(blank=True, default=list)),
                ("choice_order_map", models.JSONField(blank=True, default=dict)),
                ("exam", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="active_sessions", to="core.finalexam")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="final_exam_sessions", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [models.Index(fields=["user", "exam"], name="core_finale_user_id_2d7d31_idx")],
                "constraints": [
                    models.UniqueConstraint(fields=("user", "exam"), name="uniq_final_exam_session_user_exam"),
                ],
            },
        ),
    ]
