# Generated by Django 6.0.2 on 2026-03-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_course_publish_schedule'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='finalexamsession',
            new_name='core_finale_user_id_5d767a_idx',
            old_name='core_finale_user_id_2d7d31_idx',
        ),
    ]
