# Generated by Django 6.0.2 on 2026-03-02 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rename_core_finale_user_id_2d7d31_idx_core_finale_user_id_5d767a_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndpointRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(max_length=64)),
                ('subject_key', models.CharField(max_length=255)),
                ('window_started_at', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['scope', 'locked_until'], name='core_endpoi_scope_326fc4_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'subject_key'), name='uniq_rate_limit_scope_subject')],
            },
        ),
    ]
