# Generated by Django 6.0.2 on 2026-03-02 05:15

import uuid

from django.conf import settings
from django.core import signing
from django.db import migrations, models


def backfill_certificate_signatures(apps, _schema_editor):
    Certificate = apps.get_model("core", "Certificate")
    User = apps.get_model(settings.AUTH_USER_MODEL.split(".")[0], settings.AUTH_USER_MODEL.split(".")[1])
    Course = apps.get_model("core", "Course")
    salt = "certificate-payload-v1"
    version = 1

    for cert in Certificate.objects.all().iterator():
        if not cert.verification_code:
            code = uuid.uuid4().hex[:16].upper()
            while Certificate.objects.filter(verification_code=code).exclude(id=cert.id).exists():
                code = uuid.uuid4().hex[:16].upper()
            cert.verification_code = code

        user = User.objects.filter(id=cert.user_id).first()
        course = Course.objects.filter(id=cert.course_id).first()
        if user is None or course is None:
            continue

        payload = {
            "v": version,
            "certificate_code": cert.certificate_code,
            "verification_code": cert.verification_code,
            "user_id": int(cert.user_id),
            "student_name": user.username,
            "course_id": int(cert.course_id),
            "course_title": course.title,
            "issued_at": cert.issued_at.isoformat(),
        }
        cert.signature_version = version
        cert.signed_payload = signing.dumps(payload, salt=salt)
        cert.save(update_fields=["verification_code", "signature_version", "signed_payload"])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_videotranscodejob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='revoked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='certificate',
            name='revoked_reason',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signature_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='certificate',
            name='signed_payload',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='certificate',
            name='verification_code',
            field=models.CharField(blank=True, default='', max_length=32, unique=True),
        ),
        migrations.AddIndex(
            model_name='certificate',
            index=models.Index(fields=['verification_code'], name='core_certif_verific_7370ff_idx'),
        ),
        migrations.RunPython(backfill_certificate_signatures, migrations.RunPython.noop),
    ]
