# Generated by Django 6.0.2 on 2026-03-02 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_certificateauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verification_code', models.CharField(blank=True, default='', max_length=32)),
                ('status', models.CharField(choices=[('VALID', 'Valid'), ('REVOKED', 'Revoked'), ('INVALID_SIGNATURE', 'Invalid Signature'), ('NOT_FOUND', 'Not Found'), ('RATE_LIMITED', 'Rate Limited')], max_length=32)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('certificate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verification_logs', to='core.certificate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['verification_code', 'created_at'], name='core_certif_verific_9b6dcd_idx'), models.Index(fields=['status', 'created_at'], name='core_certif_status_4c24ac_idx')],
            },
        ),
    ]
