# Generated by Django 6.0.2 on 2026-03-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_certificateverificationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='certificate_pdf',
            field=models.FileField(blank=True, upload_to='certificates/pdfs/'),
        ),
    ]
